-- ===========================================================
-- NATIVA — script de configuração do banco de dados
--
-- COMO USAR (uma vez só):
-- 1. Crie um projeto grátis em https://supabase.com
-- 2. No menu lateral, abra "SQL Editor"
-- 3. Clique em "New query", cole TODO este arquivo, e clique em "Run"
-- 4. Pronto — a tabela é criada já com os 71 produtos do site.
--
-- Depois disso você NUNCA MAIS precisa mexer em SQL. Todo o dia a dia
-- (adicionar, editar, remover produto) é feito pela tela em admin.html.
-- ===========================================================

create table if not exists produtos (
  id          bigint generated by default as identity primary key,
  categoria   text not null,
  nome        text not null,
  slug        text not null unique,
  foto        text,
  preco       numeric(10,2) not null default 0,
  tamanhos    text not null default '',
  cores       text not null default '',
  novo        boolean not null default false,
  descricao   text not null default '',
  ativo       boolean not null default true,
  criado_em   timestamptz not null default now()
);

-- liga a segurança da tabela
alter table produtos enable row level security;

-- qualquer pessoa (o site) pode LER os produtos
drop policy if exists "Leitura publica" on produtos;
create policy "Leitura publica" on produtos
  for select using (true);

-- só quem estiver logado (a lojista, pelo admin.html) pode
-- adicionar, editar ou remover produtos
drop policy if exists "Escrita autenticada" on produtos;
create policy "Escrita autenticada" on produtos
  for all to authenticated using (true) with check (true);

-- apaga produtos de execuções anteriores deste script, pra poder rodar de novo sem duplicar
delete from produtos;

-- os 71 produtos que já existem no site (ponto de partida)
insert into produtos (categoria, nome, slug, foto, preco, tamanhos, cores, novo, descricao, ativo) values
  ('Camisetas', 'T-shirt Nativa Básica', 't-shirt-nativa-basica', NULL, 69.90, 'P;M;G;GG', 'preto;branco;cinza', true, 'Algodão penteado, corte reto essencial.', true),
  ('Camisetas', 'T-shirt Sealive Oversized', 't-shirt-sealive-oversized', NULL, 89.90, 'P;M;G;GG', 'preto;branco;verde', true, 'Malha pesada, modelagem ampla.', true),
  ('Camisetas', 'T-shirt Estampada Nativa', 't-shirt-estampada-nativa', NULL, 79.90, 'P;M;G', 'preto;marinho;dourado', false, 'Estampa exclusiva no peito.', true),
  ('Camisetas', 'T-shirt Gola V Nativa', 't-shirt-gola-v-nativa', NULL, 64.90, 'P;M;G;GG', 'branco;cinza;preto', false, 'Gola V, toque macio, corte reto.', true),
  ('Camisetas', 'T-shirt Listrada Nativa', 't-shirt-listrada-nativa', NULL, 74.90, 'P;M;G', 'marinho;branco', false, 'Listras finas, algodão premium.', true),
  ('Camisas', 'Camisa Xadrez Nativa', 'camisa-xadrez-nativa', NULL, 159.90, 'P;M;G;GG', 'verde;marrom', true, 'Flanela xadrez, bolso frontal.', true),
  ('Camisas', 'Camisa Social Slim', 'camisa-social-slim', NULL, 169.90, 'P;M;G', 'branco;azul', false, 'Tricoline, corte slim, fácil de passar.', true),
  ('Camisas', 'Camisa Linho Nativa', 'camisa-linho-nativa', NULL, 179.90, 'P;M;G;GG', 'areia;branco', false, 'Linho leve, ideal pro calor.', true),
  ('Camisas', 'Camisa Jeans Nativa', 'camisa-jeans-nativa', NULL, 154.90, 'P;M;G', 'jeans', false, 'Jeans leve, botões metálicos.', true),
  ('Polos', 'Polo Piquet Nativa', 'polo-piquet-nativa', NULL, 119.90, 'P;M;G;GG', 'preto;marinho;verde', true, 'Piquet clássico, punho canelado.', true),
  ('Polos', 'Polo Brasil Bordada', 'polo-brasil-bordada', NULL, 129.90, 'P;M;G', 'marinho;branco', true, 'Bordado exclusivo no peito.', true),
  ('Polos', 'Polo Listrada Nativa', 'polo-listrada-nativa', NULL, 124.90, 'P;M;G;GG', 'branco;azul', false, 'Listras finas, algodão macio.', true),
  ('Polos', 'Polo Slim Fit', 'polo-slim-fit', NULL, 114.90, 'P;M;G', 'preto;cinza', false, 'Corte justo, tecido leve.', true),
  ('Calças Jeans', 'Calça Jeans Slim Nativa', 'calca-jeans-slim-nativa', NULL, 189.90, '38;40;42;44', 'jeans;preto', true, 'Corte slim, elastano leve.', true),
  ('Calças Jeans', 'Calça Jeans Reta Nativa', 'calca-jeans-reta-nativa', NULL, 179.90, '38;40;42;44;46', 'jeans', false, 'Corte reto clássico, five pockets.', true),
  ('Calças Jeans', 'Calça Sarja Cargo Nativa', 'calca-sarja-cargo-nativa', NULL, 194.90, '38;40;42;44', 'preto;verde;areia', false, 'Bolsos funcionais, sarja resistente.', true),
  ('Calças Jeans', 'Calça Moletom Nativa', 'calca-moletom-nativa', NULL, 139.90, 'P;M;G;GG', 'preto;cinza;marinho', false, 'Punho elástico, conforto pro dia a dia.', true),
  ('Bermudas e Shorts', 'Bermuda Jeans Nativa', 'bermuda-jeans-nativa', NULL, 119.90, '38;40;42;44', 'jeans', false, 'Barra desfiada, five pockets.', true),
  ('Bermudas e Shorts', 'Bermuda Sarja Nativa', 'bermuda-sarja-nativa', NULL, 109.90, '38;40;42;44', 'preto;areia;verde', true, 'Sarja leve, caimento reto.', true),
  ('Bermudas e Shorts', 'Short Moletom Nativa', 'short-moletom-nativa', NULL, 79.90, 'P;M;G;GG', 'preto;cinza', false, 'Conforto pro treino ou pra casa.', true),
  ('Bermudas e Shorts', 'Bermuda Cargo Nativa', 'bermuda-cargo-nativa', NULL, 124.90, '38;40;42;44', 'verde;areia', false, 'Bolsos laterais, sarja resistente.', true),
  ('Moletom e Frio', 'Moletom Canguru Nativa', 'moletom-canguru-nativa', NULL, 159.90, 'P;M;G;GG', 'preto;cinza;marinho', true, 'Capuz e bolso canguru, forro macio.', true),
  ('Moletom e Frio', 'Moletom Careca Nativa', 'moletom-careca-nativa', NULL, 139.90, 'P;M;G;GG', 'preto;branco;verde', false, 'Gola careca, punho canelado.', true),
  ('Moletom e Frio', 'Cardigã Tricot Nativa', 'cardiga-tricot-nativa', NULL, 169.90, 'P;M;G', 'marrom;cinza', false, 'Abotoamento frontal, bolsos laterais.', true),
  ('Moletom e Frio', 'Colete Tricot Nativa', 'colete-tricot-nativa', NULL, 129.90, 'P;M;G', 'verde;marrom', false, 'Sem manga, ótimo pra camadas.', true),
  ('Jaquetas e Casacos', 'Jaqueta Corta-Vento Nativa', 'jaqueta-corta-vento-nativa', NULL, 229.90, 'P;M;G;GG', 'preto;verde', true, 'Impermeável leve, capuz destacável.', true),
  ('Jaquetas e Casacos', 'Casaco Trench Nativa', 'casaco-trench-nativa', NULL, 329.90, 'P;M;G', 'areia;preto', true, 'Corte reto longo, cinto de amarrar.', true),
  ('Jaquetas e Casacos', 'Jaqueta Jeans Nativa', 'jaqueta-jeans-nativa', NULL, 219.90, 'P;M;G;GG', 'jeans', false, 'Lavagem média, botões metálicos.', true),
  ('Jaquetas e Casacos', 'Colete Acolchoado Nativa', 'colete-acolchoado-nativa', NULL, 179.90, 'P;M;G', 'preto;verde;marinho', false, 'Leve e quentinho, ideal pra camadas.', true),
  ('Acessórios', 'Boné Nativa', 'bone-nativa', NULL, 79.90, 'Único', 'preto;verde;marinho', true, 'Aba curva, fivela ajustável.', true),
  ('Acessórios', 'Cinto Couro Nativa', 'cinto-couro-nativa', NULL, 89.90, 'Único', 'marrom;preto', false, 'Fivela metálica, couro legítimo.', true),
  ('Acessórios', 'Carteira Couro Nativa', 'carteira-couro-nativa', NULL, 99.90, 'Único', 'marrom;preto', false, 'Compacta, vários compartimentos.', true),
  ('Acessórios', 'Óculos de Sol Nativa', 'oculos-de-sol-nativa', NULL, 119.90, 'Único', 'preto;marrom', false, 'Proteção UV400, armação leve.', true);
